- include_role: {name: corpusops.roles/docker_compose_service}
  vars:
    _docker_compose_service:
      project: "{{cops_redmine_compose_project}}"
      state: "{{cops_redmine_stopped_state}}"
      working_directory: "{{cops_redmine_hostdir}}"
      stdout: "{{cops_redmine_stdout}}"
      stderr: "{{cops_redmine_stderr}}"
  tags: [service_stop]
- shell: |-
    set -ex
    if [ ! -e "{{cops_redmine_hostdir}}/{{cops_redmine_compose_files[0]}}" ];then exit 0;fi
    cd {{cops_redmine_hostdir}}
    docker-compose down
  tags: [service_dockercompose_stop]
