---
- name: Create directories
  file:
    path: "{{cops_redmine_versioned_hostdir}}/{{ item.path }}"
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: "{{playbook_dir}}/setup/"
  when: item.state == 'directory'
- name: Template files
  template:
    src: '{{ item.src }}'
    dest: "{{cops_redmine_versioned_hostdir}}/{{ item.path }}"
    mode: '{{ item.mode }}'
    trim_blocks: false
  with_filetree: "{{playbook_dir}}/setup/"
  when:
  - "item.state == 'file'"
  - "not item.path|regex_search('\\.frep$|conf.d|rclone.*\\.py')"
- name: Copy files
  copy:
    src: '{{ item.src }}'
    dest: "{{cops_redmine_versioned_hostdir}}/{{ item.path }}"
    mode: '{{ item.mode }}'
  with_filetree: "{{playbook_dir}}/setup/"
  when:
  - "item.state == 'file'"
  - "     item.path|regex_search('\\.frep$|conf.d|rclone.*\\.py')"
- name: Synchronise redminescripts
  delegate_to: "localhost"
  synchronize:
    compress: false
    ssh_args: "{{cops_redmine_sshargs}}"
    src: "./scripts/"
    dest: "{{cops_redmine_hostdir}}/scripts/"
    rsync_opts: "{{cops_redmine_code_rsync_opts}}"
    set_remote_user: "no"
  tags: [sync_redminescripts]
