---
ssh_envs:
  hosts:
    myhost.example.net:

prod-redmine:
  hosts:
    myhost.example.net: {ansible_host: myhost.example.net, ansible_port: "40001"}

prod_loc-redmine:
  hosts:
    prod_loc-redminehost: {ansible_host: localhost, ansible_connection: local}

prod:
  children:
    prod-redmine:

prod_loc:
  children:
    prod_loc-redmine:

redmine_servers:
  children:
    prod:
    prod_loc:
